### ISSUE TITLE
paralellLimit on an iterable

### ISSUE THREAD

**Issue by polkovnikov-ph** [dbushong/async-q#2]
I'm struggling with a case when one needs to do several jobs in parallel, but some more jobs are added in process. I've made an array, and `yield arr.pop()` from it in a generator function. The problem is that there's no way to pass it to any `async-q` function. The best I can do is write my own `parallelLimit` that takes an iterator object as its first argument.

Do you have any better idea?

**Comment by dbushong** [comment]
Would `queue()` do what you want?

**Comment by dbushong** [comment]
Closed due to inactivity.
