### ISSUE TITLE
Fatal error: fn.apply is not a function   

### ISSUE THREAD

**Issue by fantapop** [dbushong/async-q#7]
I was trying to use parallelLimit and getting this error.  It was a bit tricky to look into.  I'm calling parallelLimit like this:

```
asyncq.parallelLimit(promiseList, 5); 
```

I switched my coat to use throat directly and its working.

**Comment by fantapop** [comment]
actually... strike that.  I switched to using throat, I thought it was working.  But it wasn't actually limiting the concurrency.  Still trying to get that working correctly.  After some iterations of trying things, I'm getting the exact same output from throat.  fn.apply is not a function.

**Comment by dbushong** [comment]
Per [the docs](https://github.com/dbushong/async-q#paralleltasks), `parallelLimit` (like `parallel`) takes an array of **functions**, not an array of promises.
